AWSTemplateFormatVersion: '2010-09-09'
Description: Kittens Carousel Web Application

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64'

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: terraform
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo service httpd start
          sudo yum install -y git
          git clone https://github.com/raifehizlan/static-web.git
          sudo cp -r static-web/* /var/www/html/
          chmod -R 755 /var/www/html

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
Outputs:
  WebsiteURL:
    Description: URL of the Kittens Carousel Web Application
    Value: !Sub http://${EC2Instance.PublicDnsName}
